### ISSUE TITLE
Can this work on Windows?

### ISSUE THREAD

**Issue by aksigkvgithub** [zebreus/thesis-template#1]
I am a heavy statistics and mathematics user, who writes articles and some books too. I used Asciidocdor web pdf too, which has issues with large blocks of text, which I generally have while writing R codes producing large blocks of output. Sometimes tables through Asciidocdor web pdf do not align columns properly.

Can you tell how I should address these problems on Windows?

Can you demonstrate with an example as how to install your template and use it on Windows with Asciidocdor and Asciidocdor web pdf.

With regards

Dr. A. K. Singh

**Comment by zebreus** [comment]
I have not yet tried using the template with Windows, but I think it should work. The most compatible way is probably by using the WSL. I will try that later today or tomorrow and add some instructions to the Readme.

The template contains all stylesheets, so it should be possible to fix the table alignment there. Can you share an example for your problem with tables?

**Comment by zebreus** [comment]
The template works with windows. The steps below work on a fresh Windows 11 install.

### Windows

**You need at least Windows 11** (build 21364+) otherwise preview will not work (See https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg)

Detailed description of everything required to use the template on a fresh Windows:
1. Install vscode from https://code.visualstudio.com/docs/?dv=win
2. Install WSL using `wsl --install` https://learn.microsoft.com/en-us/windows/wsl/install
3. Install nix inside the WSL using `sh <(curl -L https://nixos.org/nix/install) --no-daemon` inside the WSL (Enter WSL shell with `wsl` in powershell/cmd) https://nixos.org/download.html#nix-install-windows
4. Enable nix flakes `mkdir -p ~/.config/nix && echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf`  inside the WSL.
5. Install git (Either from https://git-scm.com/download/win or use the version included in WSL ubuntu). You can keep most options at the default value, I recommend setting the setting for newlines to checkout as-is and commit with LF. This way you will have no CRLF problems. I also suggest setting the default editor to vscode.
6. Clone the template `git clone https://github.com/zebreus/thesis-template --config core.autocrlf=true`
7. Open the cloned folder in vscode
8. (Optional) Install the recommended extensions in vscode
9. Open a terminal in vscode, type `wsl` and then `nix develop`. This will drop you into a shell where asciidoctor-web-pdf and all other dependencies are available. Running `nix develop` for the first time will take a while, as all dependencies need to be downloaded.
10. You can now do all the things inside that shell. You can now build the PDF with `make pdf`, show a preview with `make preview` or do something else.

### NixOS

1. Install vscode and git
2. Clone the template with `git clone https://github.com/zebreus/thesis-template`
3. cd into the cloned folder
4. Run `nix develop` to enter a shell where asciidoctor-web-pdf and all other dependencies are available.
5. Run `code .` to open vscode
6. (Optional) Install the recommended extensions in vscode
7. You can now do all the things inside that shell. You can now build the PDF with `make pdf`

### Other linux distros

1. Install vscode and git using the package manager of your distro
2. Install the nix package manager as described in https://nixos.org/download.html#nix-install-linux
3. Enable nix flakes `mkdir -p ~/.config/nix && echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf`
4. Clone the template with `git clone https://github.com/zebreus/thesis-template`
5. cd into the cloned folder
6. Run `nix develop` to enter a shell where asciidoctor-web-pdf and all other dependencies are available.
7. Run `code .` to open vscode
8. (Optional) Install the recommended extensions in vscode
9. You can now do all the things inside that shell. You can now build the PDF with `make pdf`

**Comment by zebreus** [comment]
Please let me know if that worked for you, or if you needed to do something differently

**Comment by zebreus** [comment]
@aksigkvgithub Please let me know if it worked for you so I can close the issue.
